### PR TITLE
Added initial data for Portugal.

### PR DESCRIPTION
**Pull request by tobiastom**
This pull requests provides initial data for Portugal. If you like it, I could add more spots later.

### CODE REVIEW

**Comment by swrobel** [comment]
Thanks for the contribution! I hadn't expected anyone to add spots from outside of the US West Coast yet, so I will have to update the app to support multiple timezones before the forecasts will display correctly for this region.

**Comment by tobiastom** [comment]
That would be great. Thank you very much for this nice little project. :)

**Comment by tobiastom** [comment]
Did you have any chance to work on this? :)

**Comment by swrobel** [comment]
Unfortunately not. I will certainly let you know when I do.

**Comment by tobiastom** [comment]
Thank you!

**Comment by swrobel** [comment]
@tobiastom I just added Portugal to the site. Sorry to see that the waves are so bad there right now, but they aren't much better here in Southern California!

**Comment by tobiastom** [comment]
@swrobel Awesome, that you very much! 
Regarding the waves, I'm still very new to surfing, so any wave is good for me right now. :)

**Pull request merged**
